# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.markdown
  - turkish.markdown
  - english.markdown
  - whoami.markdown

footer: '<a href="https://www.github.com/eredotpkfr/my_n0t3s/" target="_blank">my_n0t3s</a> | <a href="https://twitter.com/eredot_pkfr" target="_blank">twitter</a> | <a href="https://github.com/eredotpkfr/" target="_blank">github</a> | <a href="https://www.erdoganyoksul.com/pgp.txt" target="_blank">pgp</a> |'
baseurl:
style: dark # dark (default) or light
listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
